// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4kV58xwnoPzMvuYWjxOZaZ_3ITsrxvY',
    appId: '1:1071066415726:web:6fd8b7412674948426dc7f',
    messagingSenderId: '1071066415726',
    projectId: 'wallet-app-420f4',
    authDomain: 'wallet-app-420f4.firebaseapp.com',
    storageBucket: 'wallet-app-420f4.firebasestorage.app',
    measurementId: 'G-R46Z3P0YS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0odv_E8GrH0R8BXmA7CwbOZuQrR27WLk',
    appId: '1:1071066415726:android:31de19da0ca89c1726dc7f',
    messagingSenderId: '1071066415726',
    projectId: 'wallet-app-420f4',
    storageBucket: 'wallet-app-420f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzM49oIsaHAyp7d8DwYKMDcr8d5uu0Us',
    appId: '1:1071066415726:ios:b2cd21723299497926dc7f',
    messagingSenderId: '1071066415726',
    projectId: 'wallet-app-420f4',
    storageBucket: 'wallet-app-420f4.firebasestorage.app',
    iosBundleId: 'com.example.walletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtzM49oIsaHAyp7d8DwYKMDcr8d5uu0Us',
    appId: '1:1071066415726:ios:b2cd21723299497926dc7f',
    messagingSenderId: '1071066415726',
    projectId: 'wallet-app-420f4',
    storageBucket: 'wallet-app-420f4.firebasestorage.app',
    iosBundleId: 'com.example.walletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4kV58xwnoPzMvuYWjxOZaZ_3ITsrxvY',
    appId: '1:1071066415726:web:97f3815534e51a8c26dc7f',
    messagingSenderId: '1071066415726',
    projectId: 'wallet-app-420f4',
    authDomain: 'wallet-app-420f4.firebaseapp.com',
    storageBucket: 'wallet-app-420f4.firebasestorage.app',
    measurementId: 'G-PEQM3VJSMV',
  );
}
